### ISSUE TITLE
Screenshot von allen Features

### ISSUE THREAD

**Issue by ValdrDarmir** [ValdrDarmir/Athletes-Hub#40]
## Was soll erledigt werden?
Screenshots von allen Features/Seiten von Athletes Hub.

## Warum soll es erledigt werden?
Design kann somit einfacher verbessert werden.

## Was ist dabei zu bedenken?
Upload der Bilder auf Google Drive

------
> Beim Bearbeiten des Issues nicht vergessen einen Branch anzulegen.
> 
> Dazu in der rechten Sidebar auf `Create a branch` unter `Development` klicken.

**Comment by Shoggomo** [comment]
Hier sind Screenshots von den meisten Features. Statistiken sind noch nicht enthalten.


[Atheletes Hub screenshots.zip](https://github.com/ValdrDarmir/Athletes-Hub/files/12856301/Atheletes.Hub.screenshots.zip)

**Comment by wuehrl-christoph** [comment]
Die restlichen Screenshots der Statistikseite
[Athletshub_Statistiks_Screenshots.zip](https://github.com/ValdrDarmir/Athletes-Hub/files/13051848/Athletshub_Statistiks_Screenshots.zip)
