### ISSUE TITLE
Rework Probability-Impact-Matrix

### ISSUE THREAD

**Issue by ValdrDarmir** [ValdrDarmir/Athletes-Hub#41]
## Was soll erledigt werden?
Rework der Probability-Impact-Matrix im Wiki

## Warum soll es erledigt werden?
Fehler ausbessern und einzelne Punkte verbessern.

## Was ist dabei zu bedenken?

------
> Beim Bearbeiten des Issues nicht vergessen einen Branch anzulegen.
> 
> Dazu in der rechten Sidebar auf `Create a branch` unter `Development` klicken.

**Comment by wuehrl-christoph** [comment]
New Version is up, should be discussed in the next meeting
