### ISSUE TITLE
Beschreibungen zu Spielen und Wettkampf hinzufügen

### ISSUE THREAD

**Issue by Shoggomo** [ValdrDarmir/Athletes-Hub#44]
## Was soll erledigt werden?
In den Screens zum Erstellen von Spielen und Wettkämpfen sollen Beschreibungen hinzugefügt werden.

## Warum soll es erledigt werden?
Damit besser geklärt ist, was ein bestimmtes Spiel genau ist und wie ein Wettkampf funktioniert.

## Was ist dabei zu bedenken?

------
> Beim Bearbeiten des Issues nicht vergessen einen Branch anzulegen.
> 
> Dazu in der rechten Sidebar auf `Create a branch` unter `Development` klicken.

**Comment by Rosti97** [comment]
**Beschreibung Wettkampf:**
> Fordere deine Freunde mit einem Wettkampf nach Liga-Modus (40 Schuss) heraus. Trage nach jeder Serie deine erreichte Punktzahl ein und siehe in Echtzeit den Stand der Teilnehmenden!

**Beschreibung Treppensteigen:**
Long version:
> Fordere deine Freunde mit dem beliebten Schießspiel Treppensteigen heraus. Pro Stufe habt ihr ein Ziel, wobei ihr einen gewissen Wert mit einer gewissen Schussanzahl erreichen müsst. Ihr schießt die jeweilige Stufe solange, bis ihr die Zielvorgabe erreicht habt. Wer schafft die meisten Stufen und wird das Spiel gewinnen?
Short verison:
> Fordere deine Freunde mit dem beliebten Schießspiel Treppensteigen heraus! Wer schafft die meisten Stufen und wird das Spiel gewinnen?

**Comment by Shoggomo** [comment]
Wird in #8 umgesetzt.
