### ISSUE TITLE
Optional: Logout Button im Sidepanel einbauen

### ISSUE THREAD

**Issue by ValdrDarmir** [ValdrDarmir/Athletes-Hub#46]
## Was soll erledigt werden?
Es soll Nutzenden möglich sein, sich einfacher Auszuloggen. Hierzu soll der Button zum Logout auch in der seitlichen Navigationsliste eingebaut werden.

## Warum soll es erledigt werden?
Verbesserung der User Experience

## Was ist dabei zu bedenken?
Einheitliches Design in der Anwendung

------
> Beim Bearbeiten des Issues nicht vergessen einen Branch anzulegen.
> 
> Dazu in der rechten Sidebar auf `Create a branch` unter `Development` klicken.

**Comment by Shoggomo** [comment]
Der Logout Button ist im Profil. Da er kaum verwendet werden wird und immer mehr Anwendungen ihn da unterbringen.
