### ISSUE TITLE
Nutzerstudie durchführen

### ISSUE THREAD

**Issue by ValdrDarmir** [ValdrDarmir/Athletes-Hub#48]
## Was soll erledigt werden?
Die Nutzerstudie muss durchgeführt werden. Die Anwendung Athletes Hub, soll auf verschiedene Elemente, wie Bedienung, Aussehen und Benutzerfreundlichkeit getestet werden.

## Warum soll es erledigt werden?
Durch solche Studien, kann die Anwendung verbessert werden. Außerdem können so Einblicke von Nutzenden gewonnen werden.

## Was ist dabei zu bedenken?
Die Studie sollte möglichst bald durchgeführt werden.

------
> Beim Bearbeiten des Issues nicht vergessen einen Branch anzulegen.
> 
> Dazu in der rechten Sidebar auf `Create a branch` unter `Development` klicken.

**Comment by Rosti97** [comment]
Folgende Termine sind für die Nutzerstudie geplant:

- Mittwoch, 25.10.23 in Fuchsmühl (bisher 4 Anmeldungen - Kategorie Hobbyschütz:innen)
- Donnerstag, 26-10.23 in München (bisher 3 Anmeldungen - Kategorie Leistungssportler:innen)
