### ISSUE TITLE
Nutzerstudie auswerten

### ISSUE THREAD

**Issue by ValdrDarmir** [ValdrDarmir/Athletes-Hub#49]
## Was soll erledigt werden?
Die Nutzerstudie soll ausgewertet werden und im Wiki hinterlegt werden.

## Warum soll es erledigt werden?
Die Task Time und andere Metriken sollen ausgewertet werden.
Sinnvolle Metriken sollen verwendet werden.
Ebenso solllen die Ergebnisse ansprechend präsentiert werden.

## Was ist dabei zu bedenken?
Datenschutz der Probanden

------
> Beim Bearbeiten des Issues nicht vergessen einen Branch anzulegen.
> 
> Dazu in der rechten Sidebar auf `Create a branch` unter `Development` klicken.

**Comment by Rosti97** [comment]
ToDo:

- [ ] Task Completion
- [ ] Notizen Codieren
- [ ] Feedback verschriftlichen

**Comment by Rosti97** [comment]
Siehe [Wiki - Nutzerstudien](https://github.com/ValdrDarmir/Athletes-Hub/wiki/16---Nutzerstudie)
