### ISSUE TITLE
Competitive Positioning erweitern

### ISSUE THREAD

**Issue by Rosti97** [ValdrDarmir/Athletes-Hub#70]
## Was soll erledigt werden?
Die Wiki-Seite zu Competitive Positioning erweitern, evtl. mit Screenshots aus den bereits erwähnten alternativen Produkten.

## Warum soll es erledigt werden?
Für eine bessere Übersicht.

## Was ist dabei zu bedenken?
/

------
> Beim Bearbeiten des Issues nicht vergessen einen Branch anzulegen.
> 
> Dazu in der rechten Sidebar auf `Create a branch` unter `Development` klicken.

**Comment by ValdrDarmir** [comment]
Wurde entfernt, da Aufarbeitung in MIT GSL  ist.
