### ISSUE TITLE
Finales Design umsetzen

### ISSUE THREAD

**Issue by Shoggomo** [ValdrDarmir/Athletes-Hub#8]
## Was soll erledigt werden?
Sobald alle Features umgesetzt sind, soll noch einmal das Design für die gesamte Anwendung überprüft und finalisiert werden.

## Warum soll es erledigt werden?
Damit alles zusammenpasst und einem einheitlichen Stil folgt.

## Was ist dabei zu bedenken?

------
> Beim Bearbeiten des Issues nicht vergessen einen Branch anzulegen.
> 
> Dazu in der rechten Sidebar auf `Create a branch` unter `Development` klicken.

**Comment by Rosti97** [comment]
Aktueller Stand neues Design
- [ ] Startseite
- [ ] Navigation
- [ ] Trainingsdoku
- [ ] Aktuelle Challenges
- [ ] Wettbewerbe
- [ ] Schießspiel
- [ ] Statistik
